apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik
          command: ["--api.insecure=true"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-service
spec:
  selector:
    app: traefik
  type: ClusterIP
  ports:
    - name: traefik-a-port
      port: 80
      targetPort: 3000
    - name: traefik-b-port
      port: 8080
      targetPort: 3001

# - /var/run/docker.sock:/var/run/docker.sock:ro
# This one os for dev to host docker to traefik container
